# Generated by Django 3.1.7 on 2021-03-11 06:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('url_name', models.CharField(max_length=20, null=True, verbose_name='网站名')),
                ('url', models.URLField(null=True, verbose_name='链接')),
                ('user_name', models.CharField(max_length=20, null=True, verbose_name='用户名')),
                ('user_password', models.CharField(max_length=128, null=True, verbose_name='密码')),
                ('remarks', models.TextField(null=True, verbose_name='备注')),
                ('establish_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户编号')),
            ],
            options={
                'verbose_name_plural': '数据',
                'db_table': 'data',
            },
        ),
    ]
