# Generated by Django 3.1.7 on 2021-03-11 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='姓名')),
                ('phone', models.CharField(default='', max_length=11, null=True)),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('department', models.CharField(default='管理层', max_length=20, null=True, verbose_name='部门')),
                ('user_type', models.CharField(max_length=5, null=True, verbose_name='用户类型')),
                ('establish_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('old_time', models.DateTimeField(null=True, verbose_name='上次登录时间')),
            ],
            options={
                'verbose_name_plural': '站点用户',
                'db_table': 'user',
            },
        ),
    ]
